### ISSUE TITLE
No results for Chinese keywords

### ISSUE THREAD

**Issue by oldherl** [MarginaliaSearch/MarginaliaSearch#111]
No results show up when I try some Chinese keywords. Example: 上海
I believe it's because the indexer doesn't know how to index those characters.

**Comment by vlofgren** [comment]
The search engine is currently only supporting English text, to keep the scope down while other issues are fixed.  

Down the line, support for other languages and alphabets are planned, but at this point it would only slow development down while not doing those languages justice.  

I'm closing the issue, because it's a deliberate trade-off at this point.

**Comment by oldherl** [comment]
OK. I understand this decision, but could you please state that limitation somewhere on the search page, maybe in the About or Tips boxes? It would reduce confusion. Thanks
